Resolving Code Review Comments
eclipse-uprotocol/up-client-zenoh-cpp pull request #12
Opened 2024-02-20 23:05 UTC by moniercoding

Reverted to sending payload and header separately while maintaining the use of serialized attributes.

2024-02-21 05:57 UTC, MelamudMichael requested changes

2024-02-21 05:57 UTC, MelamudMichael commented on lib/include/up-client-zenoh-cpp/session/zenohSessionManager.h
> +#include <up-core-api/uattributes.pb.h>
I think that you can remove the include

2024-02-21 05:57 UTC, MelamudMichael commented on lib/src/zenohRpcClient.cpp
> +    z_bytes_t payloadBytes = {.len = payload.size(), .start = reinterpret_cast<uint8_t*>(payload.data())};
why do you put the payload in the header? it should be sent as a payload ...

2024-02-21 05:57 UTC, MelamudMichael commented on lib/src/zenohUTransport.cpp
> +        options.encoding = z_encoding(Z_ENCODING_PREFIX_APP_PROTOBUF, nullptr);
not needed , the payload is not encoded as protobuf

2024-02-21 05:57 UTC, MelamudMichael commented on lib/src/zenohUTransport.cpp
> +        size_t attrSize = attributes.ByteSizeLong();
move this code to be just before the actual publishing

2024-02-21 05:57 UTC, MelamudMichael commented on lib/src/zenohUTransport.cpp
> -    z_drop(z_move(keyStr));
why did you delete this code?

2024-02-21 05:57 UTC, MelamudMichael commented on lib/src/zenohUTransport.cpp
>   * SPDX-License-Identifier: Apache-2.0
Did you run the sample code to see that everything is working?

2024-03-11 15:22 UTC, PLeVasseur commented
@moniercoding -- hey there :slightly_smiling_face: 

Seemed like this PR overlapped with #16 and #16 looked more recent. Should this one be closed in favor of that one or are different things intended for each?

2024-03-11 15:26 UTC, moniercoding commented
> @moniercoding -- hey there 🙂
> 
> Seemed like this PR overlapped with #16 and #16 looked more recent. Should this one be closed in favor of that one or are different things intended for each?

Hey @PLeVasseur, yes This should be closed in favor of #16.

2024-03-11 15:26 UTC, closed without merging