Adjusting code to use protobuf files
eclipse-uprotocol/up-client-zenoh-cpp pull request #16
Opened 2024-02-28 22:30 UTC by moniercoding

2024-02-29 13:28 UTC, MelamudMichael requested changes

2024-02-29 13:28 UTC, MelamudMichael commented on lib/src/zenohRpcClient.cpp
> +    // Serialize UAttributes
move serialization just before z_get

2024-02-29 13:28 UTC, MelamudMichael commented on lib/src/zenohRpcClient.cpp
> +        uprotocol::v1::UMessage message;
why umessage ? it should be uattributes..

2024-02-29 13:28 UTC, MelamudMichael commented on lib/src/zenohRpcClient.cpp
> +        const auto& payloadData = message.payload();
upayload should receive the data from sample.payload

2024-02-29 13:28 UTC, MelamudMichael commented on lib/src/zenohUTransport.cpp
> +    uprotocol::v1::UAttributes attributes;
use this as an example

2024-02-29 13:28 UTC, MelamudMichael commented on lib/src/zenohUTransport.cpp
> +//                                    z_encoding_t &encodingOut) noexcept {
delete this function

2024-03-11 15:19 UTC, PLeVasseur commented
Hey @moniercoding :wave: -- could you rebase this PR? Is it up for another round of review?

2024-04-04 15:44 UTC, stevenhartley commented
Pr has gone stale, closing

2024-04-04 15:44 UTC, closed without merging