moving threadpool
eclipse-uprotocol/up-client-zenoh-cpp pull request #9
Opened 2024-02-12 10:32 UTC by MelamudMichael

2024-02-13 03:53 UTC, WNewsome commented on lib/include/up-client-zenoh-cpp/rpc/zenohRpcClient.h
> +        static constexpr auto maxNumOfCuncurrentRequests_ = size_t(2);
Typo
```suggestion
        static constexpr auto maxNumOfConcurrentRequests_ = size_t(2);
```

2024-02-13 03:54 UTC, WNewsome reviewed
Typo

2024-02-21 21:59 UTC, linsonittoop commented
Update Copyright in all modified files

2024-02-21 22:05 UTC, linsonittoop requested changes
Update the Copyright in modified files

2024-02-22 10:39 UTC, MelamudMichael commented on lib/src/zenohUTransport.cpp
> +    if ((0 == payload.size()) || (nullptr == payload.data()) {
It will crash according to ZettaScale 
You send RPC request where payload is not mandatory

2024-02-22 15:51 UTC, PLeVasseur commented on lib/include/up-client-zenoh-cpp/rpc/zenohRpcClient.h
> +#include <up-cpp/utils/ThreadPool.h>
I'm not familiar with how this is built today. Seems like via CMake. I would have expected the CMakeLists.txt to contain a reference to the `up-cpp` project. How is this working atm?

2024-02-22 15:52 UTC, PLeVasseur commented on lib/include/up-client-zenoh-cpp/rpc/zenohRpcClient.h
> +#include <up-cpp/utils/ThreadPool.h>
Answering my own question: it's in [this CMakeLists.txt](https://github.com/eclipse-uprotocol/up-client-zenoh-cpp/blob/6e49a6f6b2a61ebbcb4f6f9c59533a6514ac2681/lib/CMakeLists.txt#L22).

2024-02-22 15:56 UTC, PLeVasseur commented on lib/include/up-client-zenoh-cpp/rpc/zenohRpcClient.h
> +        static constexpr auto queueSize_ = size_t(20);
I'm curious if these caps are informed by something in the spec, some engineering decisions, etc.

If you believe it's a good idea to have a capped number on these may be good to reflect to other implementations as well.

WDYT?

2024-02-26 18:14 UTC, merged